# docker run --rm -v $(pwd):/src/dev/codyn --name=codyn -it metamattj/codyn-check'
tex:
  container_name: texlive
  dockerfile: docker/Dockerfile-texlive
  build: .
  command: sh
r-check-stable:
  container_name: r_check_stable
  dockerfile: docker/Dockerfile-stable
  build: .
  volumes:
    - .:/src/codyn
  working_dir: /src
  command: bash /root/rcheck.sh
r-check-devel:
  container_name: r_check_devel
  dockerfile: docker/Dockerfile-devel
  build: .
  volumes:
    - .:/src/codyn
  working_dir: /src
  links:
    - tex
  volumes_from:
    - tex
  #environment: 
  #  - PATH: ${PATH}:/usr/local/texlive/2014/bin/x86_64-linux/
  command: bash /root/rcheck.sh
